RpcUrl: "https://bsc.getblock.io/testnet/?api_key=xxxxxx"
#调度合约操作员
PrivateKey: ""
#入金合约
TreasuryAddress: ""
#调度合约
DispatcherAddress: ""
#提现币种
WithdrawalTokenAddress: "" 
#提现合约
WithdrawalAccountAddress: ""
#跨连桥合约在调度合约位置
ChainBridgeId: 0
#提现合约阀值
WithdrawalAccountThreshold: 1000

